QUESTION
Prompt: Write a function that takes the input, gives the output, and meets the conditions below.

Input: An N x M matrix of a garden. Each cell contains an integer representing the number of carrots in that part of the garden.

Output: The number of carrots Bunny eats before falling asleep.

Conditions: Bunny starts in the center of the garden. If there are more than one center cell, Bunny starts in the cell with the largest number of carrots. There will never be a tie for the highest number of carrots in a center cell. Bunny eats all of the carrots in his cell, then looks left, right, up, and down for more carrots. Bunny always moves to the adjacent cell with the highest carrot count. If there are no adjacent cells with carrots, Bunny falls asleep.

Example test case in python: 
>>> garden1 = [[5, 7, 8, 6, 3],
               [0, 0, 7, 0, 4],
               [4, 6, 3, 4, 9],
               [3, 1, 0, 5, 8]]

>>> eat(garden1)
27  # starts at garden[1][2] = 7, eats 7 carrots, looks at the 8, 0, 3, and 0 adjacent, moves to the 8, repeat.

In [1]:
import numpy as np

In [2]:
def eat(M):
    try:
        #convert input matrix to np 2-D array
        M = np.array(M)
        rows,cols = M.shape
        center_row=[]
        center_col=[]
    
        #if there's even number of rows, append the two center rows
        if rows%2 == 0:
            center_row.extend((rows//2-1,rows//2))
        else:
            center_row=[rows//2]

        #if there's even number of columns, append the two center columns
        if cols%2 == 0:
            center_col.extend((cols//2-1, cols//2))
        else:
            center_col=[cols//2]
            
    #if the input is not a matrix, alert user
    except:
        print("Invalid input")
        raise

    #center will be identified already if there is only one center 
    #otherwise find the corrdinates of the largest center cell
    if len(center_row) == 1 and len(center_col) ==1:
        max_center_val = M[center_row[0],center_col[0]]
        max_center_col = center_col[0]
        max_center_row = center_row[0]
    
    else:
        max_center_val = M[center_row[0],center_col[0]]
        max_center_col = center_row[0]
        max_center_row = center_col[0]
        for row in center_row:
            for col in center_col:
                if max_center_val < M[row,col]:
                    max_center_val = M[row,col]
                    max_center_row = row
                    max_center_col = col
    
    #start to collect carrots!
    #collect first cell
    count = max_center_val
    current_row = max_center_row
    current_col = max_center_col
    M[current_row, current_col]=0 
    
    #check what cells avaialble around the current cell
    #if the current cell is at the edge, then there'wll be fewer than 4 cells
    while 1:
        candidates_val = []
        candidates_coord = []
        
        if current_row < rows-1:
            down = M[current_row+1,current_col]
            candidates_val.append(down)
            candidates_coord.append([current_row+1,current_col])
        else:
            down = 0
            
        if current_row > 0:
            up = M[current_row-1,current_col]
            candidates_val.append(up)
            candidates_coord.append([current_row-1,current_col])
        else:
            up = 0
            
        if current_col < cols-1:
            right = M[current_row,current_col+1]
            candidates_val.append(right)
            candidates_coord.append([current_row,current_col+1])
        else:
            right = 0
            
        if current_col > 0:
            left = M[current_row,current_col-1]
            candidates_val.append(left)
            candidates_coord.append([current_row,current_col-1])
        else:
            left = 0
            
        #if there's no resouces in all directions, break out of the while loop, bunny goes to sleep
        if left + right + up + down == 0:
            break
            
        else:
            #find the max value in all candiate cells, collect the carrot
            max_candidate_val_index = candidates_val.index(max(candidates_val))
            count += candidates_val[max_candidate_val_index]

            #update the matrix and move to the next cell
            M[current_row, current_col]=0 
            current_row, current_col = candidates_coord[max_candidate_val_index]
            
            #show the path of the bunny and the updated garden matrix
            print(current_row, current_col)
            print(M)
            
    return count

In [3]:
#even row, odd column
garden1 = [[5, 7, 8, 6, 3],
           [0, 0, 7, 0, 4],
           [4, 6, 3, 4, 9],
           [3, 1, 0, 5, 8]]

In [4]:
eat(garden1)

2 0
[[5 7 8 6 3]
 [0 0 7 0 4]
 [4 0 3 4 9]
 [3 1 0 5 8]]
3 0
[[5 7 8 6 3]
 [0 0 7 0 4]
 [0 0 3 4 9]
 [3 1 0 5 8]]
3 1
[[5 7 8 6 3]
 [0 0 7 0 4]
 [0 0 3 4 9]
 [0 1 0 5 8]]


15

In [5]:
#even row, even column
garden2 = [[5, 7, 8, 6, 3],
            [0, 6, 7, 0, 4],
            [4, 6, 3, 4, 9],
            [4, 6, 3, 4, 9],
            [3, 1, 0, 5, 8]]

In [6]:
eat(garden2)

1 2
[[5 7 8 6 3]
 [0 6 7 0 4]
 [4 6 0 4 9]
 [4 6 3 4 9]
 [3 1 0 5 8]]
0 2
[[5 7 8 6 3]
 [0 6 0 0 4]
 [4 6 0 4 9]
 [4 6 3 4 9]
 [3 1 0 5 8]]
0 1
[[5 7 0 6 3]
 [0 6 0 0 4]
 [4 6 0 4 9]
 [4 6 3 4 9]
 [3 1 0 5 8]]
1 1
[[5 0 0 6 3]
 [0 6 0 0 4]
 [4 6 0 4 9]
 [4 6 3 4 9]
 [3 1 0 5 8]]
2 1
[[5 0 0 6 3]
 [0 0 0 0 4]
 [4 6 0 4 9]
 [4 6 3 4 9]
 [3 1 0 5 8]]
3 1
[[5 0 0 6 3]
 [0 0 0 0 4]
 [4 0 0 4 9]
 [4 6 3 4 9]
 [3 1 0 5 8]]
3 0
[[5 0 0 6 3]
 [0 0 0 0 4]
 [4 0 0 4 9]
 [4 0 3 4 9]
 [3 1 0 5 8]]
2 0
[[5 0 0 6 3]
 [0 0 0 0 4]
 [4 0 0 4 9]
 [0 0 3 4 9]
 [3 1 0 5 8]]


51

In [7]:
#single(odd) row, odd column
garden3 = [[5, 7, 8, 6, 3]]

In [8]:
eat(garden3)

0 1
[[5 7 0 6 3]]
0 0
[[5 0 0 6 3]]


20

In [9]:
#odd row, single(odd)  column
garden4 = [[5], [7], [8], [6], [3]]

In [10]:
eat(garden4)

1 0
[[5]
 [7]
 [0]
 [6]
 [3]]
0 0
[[5]
 [0]
 [0]
 [6]
 [3]]


20

In [11]:
#single row, single column
garden5 = [[5]]

In [12]:
eat(garden5)

5